### ISSUE TITLE
Tagging ontology

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#243]
Here is an initial take on tags - not completely developed. going to add to it as i go through my course. feedback welcome!

Week 1 - lessons - tag additions
- [x] change tags2 --> topics
- [x] change topics --> subtopics in the _data/topics.yml file
- [x] change all lessons to use topics rather than tags 2
- [x] trying spectral-remote-sensing out as a category
- [x] adding flood-erosion as a science tag
- [x] Create issue to figure out time series subcategories that fit what we have 
- [x] Visualization -- move to data analysis & exploration  
- [x] Is data-management really scientific programming or is it open rscience ?
- [x] Currently the tag pages have a "by date" order. There is likely a better way to organize the lessons but we need to think more about what that should be. If they are part of a set we could organize them sequentially but that will get complicated. 
- [x] Where do we fit dealing with NA and missing  missing-data ?? - new issue?
- [x] Change File type -> file-format
- [x] Remove R from the scientific programming list
- [x] Create open science topic 
        - Open science
        - publication, dois,
        - public code / github
- [x] change - reproducible-open-science -> reproducible-science-and-programming
subtopics:
    - Automation
    - markdown
    - jupyter notebooks
    - R-studio
    - data management
    - git
- [x] on .md pages, change main-tag to is-main-topic
    - is-main-topic
- [ ] Close this issue and move list below to wiki 
```
topics:
  remote-sensing:
    subtopics: ['landsat', 'modis', 'lidar', 'naip', 'spectral-remote-sensing']
  earth-science:
    subtopics: ['fire', 'permafrost', 'flood-erosion', 'vegetation', 'uncertainty']
 social-science:
   subtopics: ['social-media']  
  file-formats: 
    subtopics: ['hdf5', 'json', 'csv', 'raster',  'shapefile', 'geotiff']
  data-analysis-and-exploration:
    subtopics: ['machine-learning', 'text-mining', 'data-visualization']
  spatial-data-and-gis:
    subtopics: ['raster-data', 'vector-data', 'coordinate-reference-systems']
  time-series:
    subtopics: ['convert-date-time',  'epoch',  'julian-day', 'day-of-year']
  open-science:
    subtopics: ['github', 'rmarkdown',  'jupyter-notebooks']
  reproducible-science-and-programming:
    subtopics: ['literate-expressive-programming', 'functions',  'r-studio',  'automate-science-workflows', 'git', 'markdown'] 
  find-and-manage-data: 
     subtopics: ['data-management', 'find-data', 'metadata']
```

** is it work considering words associated with a lesson rather than a package? normally people arent searching on package rather how to plot, ggplot, dplyr, pipes, etc...
